# ============================================================
# YC Batch Trends — Analysis & Visualization
# Article: [link once published]
# Data: ../data/yc_batch_trends.csv (generated by build_dataset.py)
# Requirements: tidyverse, ggrepel
# ============================================================

library(tidyverse)
library(ggrepel)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

yc_data <- read.csv("../data/yc_2026_enriched.csv")
trends   <- read_csv("../data/yc_batch_trends.csv")

# ── Setup ──────────────────────────────────────────────────────────────────
ai_tags <- c(
  "AI",
  "AI Assistant",
  "AI-Enhanced Learning",
  "AI-powered Drug Discovery",
  "AIOps",
  "Artificial Intelligence",
  "Conversational AI",
  "Deep Learning",
  "Generative AI",
  "Machine Learning"
)

crypto_tags <- c(
  "Blockchain",
  "Crypto / Web3",
  "Cryptocurrency",
  "DeFi",
  "NFT"
)

trends %>%
  filter(dimension == "tag") %>%
  distinct(value) %>%
  filter(str_detect(value, regex("agent|agentic|autonomous|copilot|assistant", ignore_case = TRUE))) %>%
  arrange(value) %>%
  print(n = 30)

trends_tags <- trends %>%
  filter(dimension == "tag") %>%
  mutate(value = case_when(
    value %in% ai_tags     ~ "AI & Agents",
    value %in% crypto_tags ~ "Crypto & Blockchain",
    TRUE                   ~ value
  )) %>%
  filter(value %in% c("AI & Agents", "Crypto & Blockchain", "Robotics", "Fintech")) %>%
  group_by(batch, batch_date, value) %>%
  summarise(
    share          = sum(count) / first(total_companies),
    total_companies = first(total_companies),
    .groups = "drop"
  ) %>%
  mutate(batch_date = as.Date(batch_date))

top_industries <- c("B2B", "Consumer", "Fintech", "Healthcare", "Industrials", "Infrastructure")

trends_ind <- trends %>%
  filter(dimension == "industry", value %in% top_industries) %>%
  mutate(batch_date = as.Date(batch_date))

latest_batch <- trends %>%
  filter(dimension == "industry") %>%
  slice_max(as.Date(batch_date), n = 1) %>%
  pull(batch) %>%
  first()


# ── Plot 1: Tag share over time (line) ─────────────────────────────────────
trends_tags %>%
  ggplot(aes(x = batch_date, y = share, color = value)) +
  geom_line() + geom_point() +
  scale_y_continuous(labels = scales::percent) +
  labs(
    title = "YC tag share over time",
    x     = NULL, y = "Share of batch", color = "Tag"
  )


# ── Plot 2: Industry share over time (line) ────────────────────────────────
trends_ind %>%
  ggplot(aes(x = batch_date, y = share, color = value)) +
  geom_line() + geom_point() +
  scale_y_continuous(labels = scales::percent) +
  labs(
    title = "YC industry share over time",
    x     = NULL, y = "Share of batch", color = "Industry"
  )


# ── Plot 3: Industry composition over time (stacked area) ──────────────────
trends_ind %>%
  ggplot(aes(x = batch_date, y = share, fill = value)) +
  geom_area(alpha = 0.8, position = "stack") +
  scale_y_continuous(labels = scales::percent) +
  labs(
    title = "YC industry composition over time",
    x     = NULL, y = "Share of batch", fill = "Industry"
  )

# ── Plot 4: Industry × batch heatmap ───────────────────────────────────────
trends_ind %>%
  ggplot(aes(x = batch_date, y = value, fill = share)) +
  geom_tile(color = "white") +
  scale_fill_gradient(low = "white", high = "#F26522", labels = scales::percent) +
  labs(
    title = "Industry share heatmap",
    x     = NULL, y = NULL, fill = "Share"
  )


# ── Plot 5: Tag share over time (stacked area) ─────────────────────────────
trends_tags %>%
  ggplot(aes(x = batch_date, y = share, fill = value)) +
  geom_area(alpha = 0.8, position = "stack") +
  scale_y_continuous(labels = scales::percent) +
  labs(
    title = "YC tag composition over time",
    x     = NULL, y = "Share of batch", fill = "Tag"
  )


# ── Plot 6: Tag × batch heatmap ────────────────────────────────────────────
trends_tags %>%
  ggplot(aes(x = batch_date, y = value, fill = share)) +
  geom_tile(color = "white") +
  scale_fill_gradient(low = "white", high = "#F26522", labels = scales::percent) +
  labs(
    title = "Tag share heatmap",
    x     = NULL, y = NULL, fill = "Share"
  )
